---
- name: "MMN cacert - Update trust store"
  become: True
  ansible.builtin.command: "{{ cacert_command_updatetruststore }}"
  changed_when: false
  when:
    - ansible_distribution != 'OpenWrt'
    - not cacert_runimagebuilder | default(false) | bool
