---
galaxy_info:
  role_name: ansible_netboxnewdevice
  author: Jochen Demmon
  description: Interactive wizard that creates a new device in Netbox via the netbox.netbox collection.
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags: [netbox, dcim, inventory, device]
dependencies: []
