---
# handlers file for ansible_podman
- name: Restart podman openwrt
  community.general.openwrt_init:
    state: restarted
    name: podman
  when:
    - not podman_runimagebuilder | default(false) | bool

- name: Restart podman system prune timer
  ansible.builtin.systemd:
    name: podman-system-prune.timer
    state: restarted
    daemon_reload: true
