---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Restart syncthing for {{ syncthing_user.username }}
  ansible.builtin.systemd:
    name: "syncthing@{{ syncthing_user.username }}"
    state: restarted
