- name: Search for existing certificate
  ansible.builtin.find:
    paths: "{{ openwrt_uhttpd_cert_searchpath | dirname }}"
    file_type: directory
    patterns: "{{ inventory_hostname }}*"
  register: certdirs

- name: Set the first matching certificate directory (if exists)
  ansible.builtin.set_fact:
    actual_cert_path: "{{ certdirs.files[0].path }}"
  when:
    - certdirs.matched > 0

- name: Search for existing cert
  ansible.builtin.stat:
    path: "{{ actual_cert_path }}/{{ inventory_hostname }}.cer"
  register: searchcert
  when:
    - actual_cert_path is defined

- name: Search for existing key
  ansible.builtin.stat:
    path: "{{ actual_cert_path }}/{{ inventory_hostname }}.key"
  register: searchkey
  when:
    - actual_cert_path is defined

- name: Debug certificate search result
  ansible.builtin.debug:
    msg: "Cert found? {{ searchcert }}"
  when:
    - actual_cert_path is defined

- name: Overwrite defaults with found cert and key
  ansible.builtin.set_fact:
    openwrt_uhttpd_main_cert: "{{ searchcert.stat.path }}"
    openwrt_uhttpd_main_key: "{{ searchkey.stat.path }}"
  when:
    - searchkey is defined
    - searchcert is defined
    - searchkey.stat is defined
    - searchkey.stat.exists
    - searchcert.stat.exists
