---
- name: "MMN chrony - Disable systemd-timesyncd"
  ansible.builtin.service:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  when: ansible_service_mgr == "systemd"
  register: chronyd_timesyncd_disable
  failed_when:
    - chronyd_timesyncd_disable.failed
    - "'not found' not in chronyd_timesyncd_disable.msg | default('')"
    - "'Could not find' not in chronyd_timesyncd_disable.msg | default('')"

- name: "MMN chrony - Enable chrony service"
  ansible.builtin.service:
    name: "{{ chronyd_servicename }}"
    state: started
    enabled: true
  register: chronyd_service_enable
  failed_when:
    - chronyd_service_enable.failed
    - "'not found' not in chronyd_service_enable.msg | default('')"
    - "'not been booted' not in chronyd_service_enable.msg | default('')"
