---
- name: "MMN chrony - Load OS-specific variables"
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- name: "MMN chrony - Run input validation"
  ansible.builtin.include_tasks: checks.yml

- name: "MMN chrony - Install package"
  ansible.builtin.include_tasks: 01packages.yml

- name: "MMN chrony - Configure chrony"
  ansible.builtin.include_tasks: 02configure.yml

- name: "MMN chrony - Manage services"
  ansible.builtin.include_tasks: 03services.yml
