---
galaxy_info:
  role_name: ansible_vmalert
  author: Jochen Demmer
  description: Renders vmalert rule files for a podman container.
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - "bookworm"
        - "bullseye"
        - "trixie"
    - name: Fedora
      versions:
        - "40"
        - "41"
        - "42"
        - "43"
        - "44"
  galaxy_tags: [vmalert, victoriametrics, prometheus, monitoring, alerts, container, podman]
dependencies: []
