---
# PRIVATE KEY FOR SERVER CERT

- name: "MMN cacert - Private Key for server cert block"
  when: cacert_ca.value.state | default('present') == 'present'
  block:
    - name: "MMN cacert - Make sure server key directory exists"
      become: "{{ _cacert_become }}"
      ansible.builtin.file:
        state: directory
        path: "{{ cacert_openssl_path_key_server }}"
        mode: "0755"
      delegate_to: "{{ _cacert_target_host }}"

    - name: "MMN cacert - Create server private keys"
      become: "{{ _cacert_become }}"
      community.crypto.openssl_privatekey:
        path: "{{ cacert_path_serverkey }}"
        passphrase: "{{ cacert_servercert_passphrase | default(omit) }}"
        size: "{{ cacert_servercert_bitsize | default('4096') }}"
        type: "{{ cacert_servercert_type | default('RSA') }}"
        curve: "{{ cacert_servercert_curve | default(omit) }}"
        mode: "0600"
      delegate_to: "{{ _cacert_target_host }}"

    - name: "MMN cacert - Make sure additional paths exist"
      become: "{{ _cacert_become }}"
      ansible.builtin.file:
        state: directory
        path: "{{ additionalpaths.dest }}"
      loop: "{{ cacert_serverkey_additionalpaths }}"
      loop_control:
        loop_var: "additionalpaths"
      when:
        - cacert_serverkey_additionalpaths is defined
        - additionalpaths.state | default('present') == 'present'
        - not cacert_runimagebuilder | default(false) | bool
      delegate_to: "{{ _cacert_target_host }}"

    - name: "MMN cacert - Write server private keys to additional paths"
      become: "{{ _cacert_become }}"
      ansible.builtin.copy:
        src: "{{ cacert_path_serverkey }}"
        remote_src: True
        dest: "{{ additionalpaths.dest }}/{{ cacert_filename_serverkey }}"
        mode: "0600"
        owner: "{{ additionalpaths.user | default(omit) }}"
        group: "{{ additionalpaths.group | default(omit) }}"
      loop: "{{ cacert_serverkey_additionalpaths }}"
      loop_control:
        loop_var: "additionalpaths"
      when:
        - cacert_serverkey_additionalpaths is defined
        - additionalpaths.state | default('present') == 'present'
        - not cacert_runimagebuilder | default(false) | bool
      delegate_to: "{{ _cacert_target_host }}"

- name: "MMN cacert - Remove server private key"
  become: "{{ _cacert_become }}"
  ansible.builtin.file:
    path: "{{ cacert_path_serverkey }}"
    state: absent
  when: cacert_ca.value.state | default('present') == 'absent'
  delegate_to: "{{ _cacert_target_host }}"

- name: "MMN cacert - Remove server private key from additional paths"
  become: "{{ _cacert_become }}"
  ansible.builtin.file:
    path: "{{ additionalpaths.dest }}/{{ cacert_filename_serverkey }}"
    state: absent
  loop: "{{ cacert_serverkey_additionalpaths }}"
  loop_control:
    loop_var: "additionalpaths"
  when:
    - cacert_serverkey_additionalpaths is defined
    - (additionalpaths.state | default('present') == 'absent') or (cacert_ca.value.state | default('present') == 'absent')
    - not cacert_runimagebuilder | default(false) | bool
  delegate_to: "{{ _cacert_target_host }}"
