---
- name: "MMN cacert - Assemble CA vars for target host"
  ansible.builtin.set_fact:
    cacert_filename_cacert: "{{ cacert_ca.key }}_ca_{{ cacert_tag_certificate }}.{{ cacert_openssl_suffix_certificate_ca }}"
    cacert_filename_cakey: "{{ cacert_ca.key }}_ca_{{ cacert_tag_privatekey }}.pem"

- name: "MMN cacert - CA cert destination path on target host"
  ansible.builtin.set_fact:
    cacert_path_cacert_targethost: "{{ cacert_openssl_path_certificate_ca }}/{{ cacert_filename_cacert }}"
