---
# tasks file for ansible_openwrtnetwork
- name: merge interfaces from group and host definitions
  include_tasks: merge.yml

- name: iproute tasks
  when: openwrt_network_routing_tables is defined
  block:
    - name: Make sure iproute2 deploypath exists
      ansible.builtin.file:
        path: "{{ openwrt_network_iproute2_deploypath }}"
        state: directory
    - name: Create routing tables
      ansible.builtin.template:
        src: rt_tables.jinja2
        dest: "{{ openwrt_network_iproute2_deploypath }}/{{ openwrt_network_iproute2_deployfile }}"
        mode: 0600

# Wireguard
- name: make sure wireguard management dir exists
  ansible.builtin.file:
    path: "{{ openwrt_network_wg_keypath }}"
    state: directory
    mode: 0700
  when: openwrt_network_wg_keypath is defined
  delegate_to: 127.0.0.1
  become: false
- name: run wg server tasks
  include_tasks: wg_server.yml
  loop: "{{ openwrt_network_interfaces | dict2items }}"
- name: run wg peers tasks
  include_tasks: wg_client.yml
  loop: "{{ openwrt_network_wireguardpeers | dict2items }}"
  when: openwrt_network_wireguardpeers is defined
- name: Make sure network deploypath exists
  ansible.builtin.file:
    path: "{{ openwrt_network_deploypath }}"
    state: directory

# HA Tasks
- name: Run Tasks for HA setup
  ansible.builtin.include_tasks: ha.yml
  when: openwrt_network_hamaster is defined or openwrt_network_habackup is defined

- name: MMN openwrtnetwork - Check if interfaces are present
  pause:
    prompt: "Neither interfaceshost nor interfacesgroup is defined. Do you still want to deploy network config? [yes/no]"
  register: openwrt_network_interfacesdeploybool
  when:
    - openwrt_network_interfacesgroup is undefined
    - openwrt_network_interfaceshost is undefined

- name: MMN openwrtnetwork - Check if devices are present
  pause:
    prompt: "Neither deviceshost nor devicesgroup is defined. Do you still want to deploy network config? [yes/no]"
  register: openwrt_network_devicesdeploybool
  when:
    - openwrt_network_devicesgroup is undefined
    - openwrt_network_deviceshost is undefined

# Main Network Deployment Tasks
- name: Deploy Network configuration
  ansible.builtin.template:
    src: network.jinja2
    dest: "{{ openwrt_network_deploypath }}/{{ openwrt_network_deployfile }}"
    backup: "{{ openwrt_network_backupconfig | default(false) }}"
    mode: 0600
  when: 
    - openwrt_network_interfacesdeploybool.user_input is undefined or openwrt_network_interfacesdeploybool.user_input == 'yes'
    - openwrt_network_devicesdeploybool.user_input is undefined or openwrt_network_devicesdeploybool.user_input == 'yes'
  notify: restart network
