---
- name: MMN users - Setting OS variables
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"
  when: system_users is defined

# this should be optimized. The role for packages should be called instead of using builtin.package
- name: MMN users - Install OpenWrt specific packages
  ansible.builtin.package:
    name: "{{ system_users_additional_packages }}"
    state: present
  when: ansible_facts['os_family'] == "OpenWrt"

- name: check and deploy block
  block:
    - name: MMN users - Ensure users dictionary has a hosts attribute
      ansible.builtin.set_fact:
        list_of_users: []
    - name: MMN users - check what users shall be deployed on host
      ansible.builtin.include_tasks: "02check_if_user_shall_be_deployed.yml"
      loop: "{{ system_users | dict2items }}"
      loop_control:
        loop_var: user
    - name: MMN users - Deploy users
      ansible.builtin.include_tasks: "03live_runusers.yml"
      loop: "{{ system_users | dict2items }}"
      loop_control:
        loop_var: user
  when: system_users is defined

- name: MMN users - Fail status feedback
  ansible.builtin.debug:
    msg: "The role system_users did not run on host {{ inventory_hostname }} because the var system_users is not set."
  when: system_users is not defined
