---
# handlers file for ansible_pdnsrecursor/
- name: restart pdnsrec
  service:
    name: pdns-recursor
    state: restarted

- name: restart pdnsrecursor container
  ansible.builtin.command:
    cmd: "podman restart {{ pdnsrec_containername | default('pdnsrecursor0') }}"
  changed_when: true
