---
galaxy_info:
  role_name: ansible_groups
  author: Jochen Demmer
  description: Configures posix groups
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
    - name: Ubuntu
    - name: Alpine
    - name: ArchLinux
    - name: EL
    - name: Fedora
    - name: FreeBSD
    - name: OpenWrt
  galaxy_tags: [posix, groups, group]
dependencies: []
