---
- name: MMN sshkeys - Setting OS variables 
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"

  # COMMON LINUX TASKS
- import_tasks: 001_commonlinux.yml
  when: ansible_facts['os_family'] == 'Alpine'
- import_tasks: 001_commonlinux.yml
  when: ansible_facts['os_family'] == 'RedHat'
- import_tasks: 001_commonlinux.yml
  when: ansible_facts['os_family'] == 'FreeBSD'
- import_tasks: 001_commonlinux.yml
  when: ansible_facts['os_family'] == 'Debian'
- import_tasks: 001_commonlinux.yml
  when: ansible_facts['os_family'] == 'FreeBSD'
- import_tasks: 001_commonlinux.yml
  when: ansible_facts['os_family'] == 'Archlinux'
- import_tasks: 004_collect_sshdata_commonlinux.yml
  when:
    - system_sshkeys_collect_data | default(false)
    - ansible_facts['os_family'] != 'OpenWrt'

  # OPENWRT TASKS
- import_tasks: 101_openwrt.yml
  when: ansible_facts['os_family'] == 'OpenWrt'
# TODO: This task is NOT fit to run, repair!
# - import_tasks: 104_collect_sshdata_openwrt.yml
#   when:
#     - system_sshkeys_collect_data | default(false)
#     - ansible_facts['os_family'] == 'OpenWrt'


  # TARGET OS INDEPENDENT TASKS
- name: MMN sshkeys - Write ssh_host_keys dictionary to an Ansible vars file on the Ansible controller host
  ansible.builtin.copy:
    content: |
      ---
      # Generated by Ansible - Host SSH Public Keys
      ssh_host_keys:
      {% for host in ansible_play_hosts %}
      {% set host_keys = (hostvars[host]['host_ssh_dict_openwrt'] | default({}) | combine(hostvars[host]['host_ssh_dict_nonopenwrt'] | default({}), recursive=True))[host] | default({}) %}
      {% if host_keys %}
        {{ host }}:
          {{ host_keys | to_nice_yaml(indent=2) | indent(4) }}
      {% endif %}
      {% endfor %}
    dest: "{{ system_sshkeys_collect_data_filepath }}/{{ system_sshkeys_collect_data_filename }}"
    mode: '0644'
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - system_sshkeys_collect_data | default(false)
    - ansible_facts['os_family'] == 'OpenWrt'
