galaxy_info:
  author: Jochen Demmer
  description: Deploys and configures dnsdist DNS loadbalancer (bare-metal or container)
  license: BSD-3-Clause
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: [all]
    - name: Alpine
      versions: [all]
  galaxy_tags:
    - dns
    - loadbalancer
    - powerdns
dependencies: []
