---
# handlers file for ansible_psqlserver
- name: restart postgres
  ansible.builtin.service:
    name: "{{ psqlserver_servicename }}"
    state: restarted
- name: reload postgres
  ansible.builtin.service:
    name: "{{ psqlserver_servicename }}"
    state: reloaded
- name: restart postgres container
  ansible.builtin.service:
    name: "{{ ('container-' ~ psqlserver_instance.key) if not (podman_use_quadlet | default(false) | bool) else psqlserver_instance.key }}"
    state: restarted
- name: reload postgres container
  community.postgresql.postgresql_query:
    login_port: 55432
    login_host: localhost
    login_user: postgres
    login_password: "{{ psqlserver_instance.value.password_admin }}"
    query: SELECT pg_reload_conf();
