---
# defaults file for ansible_groups
# Default empty dictionaries to prevent errors when accessing keys
system_groups_create_on_hostgroups: {}
system_groups_create_on_hosts: {}

# Imagebuilder mode: where to deploy uci-defaults scripts on the build host
system_groups_setpassword_deploypath: "{{ system_groups_setpassword_deployroot }}/etc/uci-defaults/"
system_groups_setpassword_deployfile: "99-set-group"
