---
- name: MMN Packages - Merge packages_remove from all groups this host is a member of
  ansible.builtin.set_fact:
    packages_removemergedgroup: "{{ packages_removegroup.keys() | list | intersect(group_names) | map('extract', packages_removegroup) | list | flatten }}"
  when: packages_removegroup is defined

# OpenWrt imagebuilder specific stuff
- name: MMN Packages - Set seperator if imagebuilder
  ansible.builtin.set_fact:
    packages_separator: ' '
  when: packages_runimagebuilder | default(false)
- name: MMN Packages - Set separator if not imagebuilder
  ansible.builtin.set_fact:
    packages_separator: ','
  when: not packages_runimagebuilder | default(false)

# Combine into one list and remove duplicates
- name: MMN Packages - Combine lists into packages_remove var
  ansible.builtin.set_fact: 
    packages_remove: "{{ [packages_removemergedgroup, packages_removehost, packages_removerole] | select('defined') | flatten | unique }}"
- name: MMN Packages - Remove duplicates from packages_remove list
  ansible.builtin.set_fact:
    packages_remove: "{{ packages_remove | unique }}"

