---
# Update Cache for different OSes
- name: "MMN Packages - Updating cache apk"
  community.general.apk:
    update_cache: true
  changed_when: false
  when: ansible_facts['distribution'] | default('') in ["Alpine", "OpenWrt"]

- name: "MMN Packages - Updating cache Debian based OS"
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  when: ansible_facts['os_family'] | default('') == "Debian"

- name: "MMN Packages - Updating cache Arch based OS"
  community.general.pacman:
    update_cache: true
  changed_when: false
  when: ansible_facts['os_family'] | default('') == "ArchLinux"

- name: "MMN Packages - Updating cache RedHat based OS"
  ansible.builtin.dnf:
    update_cache: true
  changed_when: false
  when:
    - ansible_facts['os_family'] | default('') == "RedHat"
    - ( ansible_facts['distribution_version'] | default('0') | float | round(0, 'floor') | int ) > 7

- name: "MMN Packages - Updating cache RedHat based OS (yum legacy)"
  ansible.builtin.yum:
    update_cache: true
    use_backend: "yum"
  changed_when: false
  when:
    - ansible_facts['os_family'] | default('') == "RedHat"
    - ( ansible_facts['distribution_version'] | default('0') | float | round(0, 'floor') | int ) < 8
