---
- name: MMN Packages - List of packages to be removed
  debug:
    var: packages_remove
- name: MMN Packages - Uninstalling packages non OpenWrt
  ansible.builtin.package:
    name: "{{ packages_remove }}"
    state: absent
  when:
    - packages_remove
    - ansible_distribution != 'OpenWrt' and ansible_distribution != 'LEDE'
    - not packages_runimagebuilder | default(false)
- name: MMN Packages - Uninstalling packages OpenWrt
  ansible.builtin.opkg:
    name: "{{ packages_remove | join(packages_separator) }}"
    state: absent
    update_cache: true
  when:
    - packages_remove
    - ansible_distribution == 'OpenWrt' or ansible_distribution == 'LEDE'
    - not packages_runimagebuilder | default(false)
