---
# tasks file for ansible_nginx
- name: include OS vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
- name: Install components
  ansible.builtin.include_tasks: install.yml
- name: Preparations
  ansible.builtin.include_tasks: prepare.yml
- name: Configurations
  ansible.builtin.include_tasks: configure.yml
- name: Setup nginx server items task
  ansible.builtin.include_tasks: servers.yml
  loop: "{{ nginx_servers }}"
  loop_control:
    loop_var: serveritem
  when: nginx_servers is defined
- name: enable nginx
  ansible.builtin.service:
    name: "{{ nginx_servicename }}"
    enabled: yes
    state: started

