---
# handlers file for ansible_openwrtusteer
- name: Restart usteer
  ansible.builtin.service:
    name: "usteer"
    state: restarted
  when:
    not openwrt_usteer_runimagebuilder | default(false)
