---
- name: restart dnsdist
  ansible.builtin.service:
    name: dnsdist
    state: restarted

- name: restart dnsdist container
  ansible.builtin.command:
    cmd: "podman restart {{ dnsdist_containername | default('dnsdist0') }}"
  changed_when: true
