---
- name: restart dnsdist
  ansible.builtin.service:
    name: dnsdist
    state: restarted

- name: restart dnsdist container
  ansible.builtin.systemd:
    name: "{{ dnsdist_containername | default('dnsdist0') }}"
    state: restarted
    daemon_reload: true
