galaxy_info:
  author: Jochen Demmer
  description: Deploys and configures blocky DNS adblocker/proxy
  license: BSD-3-Clause
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: [all]
  galaxy_tags:
    - dns
    - adblock
    - blocky
dependencies: []
