---
syncthing_packagename: "syncthing"
syncthing_default_gui_cert: "/etc/ssl/certs/main_jochenit_{{ inventory_hostname }}_certificate.pem"
syncthing_default_gui_key: "/etc/ssl/private/main_jochenit_{{ inventory_hostname }}_privatekey.pem"
